on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          monorepo-tags: true
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shaunxu'
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - run: npx nx run-many --target=build --all
        if: ${{ steps.release.outputs.releases_created }}
      - run: node ./tools/publish.js '${{toJSON(steps.release.outputs)}}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}
      - uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: 'https://enii9drexlf69.x.pipedream.net'
          webhook_secret: 1Y0uR5ecr3t1
          data: ${{ steps.release.outputs }}
        if: ${{ steps.release.outputs.releases_created }}
